### ISSUE TITLE
any way to prevent emails when "starting" stories in Estimator

### ISSUE THREAD

**Issue by rliebling** [ScientificRevenue/backlogger#8]
As the Estimator project gets populated and the stories are "started" i'm getting emails for that event.  This may be limited to stories that I'm already associated with in some way, or maybe just because i have told pivotal to email me notifications for all started stories or some such.  

It would be nice if there were a way to prevent these emails in this case.  Maybe that could be by moving them from icebox to the backlog/current instead of "starting" them.  Maybe some other way.

**Comment by spfrommer** [comment]
There's no way to change the email settings from the api (the two that are offered are read-only). However, you can change the settings for your user, including ignoring state changes, at:
https://www.pivotaltracker.com/notification_settings

Here is my understanding as to your 2nd paragraph suggestion: in the Estimator backlog, all the stories have to either be "started" and above or all "unstarted." This is because pivotal doesn't allow started and above stories to mix with unstarted stories, even if they are both in the pivotal current/backlog. To avoid starting the stories, they would all have to be unstarted, which (though trivial to implement) is undesirable for a number of reasons: a) This would still trigger an email b) You lose distinction between "finished," "rejected," etc. c) You can't assign points to stories unless they are started. I don't see a way around this other than to change the email settings manually (let me know if you get an idea).

**Comment by rliebling** [comment]
@spfrommer Good points.  I didn't think about the impact on ability to order the stories.  One minor correction, though, is your point c) i believe is false.  You can assign points to unstarted stories.  But, your other points are convincing.

**Comment by rliebling** [comment]
is there any way to import them into the Estimator as "Started" to avoid the state change?

**Comment by spfrommer** [comment]
Yes, I can try doing that.

**Comment by spfrommer** [comment]
Hi Rich,
Sorry that things are taking a while. It looks like I'm already setting the state simultaneously with moving the story.
